### ISSUE TITLE
/faq faq:Configuration new section for structure rarity or deletion

### ISSUE THREAD

**Issue by Tera458** [catter1/Incendy#60]
Multiple people have been asking how to delete some structure or change their rarity since the abandonment of the structure disabler by Apollo and and that other ai made pack that allegedly did that so I wrote a brief tutorial.

This tutorial will briefly explain how to change a structure's rarity or disable it.
To change the rarity:
* Open the desired project's `\data\project\worldgen\structure_set` folder.
* Find the `.json` of the structure you wish to alter.
* To change its rarity, open the corresponding `.json`. You can then tweak `spacing`, which is the average distance in chunks the same structure set will have from each other, and the `separation`, which is the minimum chunks the same structure set will be able to appear from each other. Alternatively, you can add or modify a `"frequency": X,` line with a value in between 0 and 1 (inclusive) which corresponds to the % of chance the structure will spawn if meeting all the other conditions. Once you're done, save.
To entirely prevent the set from spawning:
* Open the structure's corresponding `.json` in the` \data\project\worldgen\structure` folder.
* On the `"biomes":` line, delete everything between the square brackets ( `[ ]` ) and save.

Now give the b#tches back

**Comment by catter1** [comment]
Added in 3.0.16
